### ISSUE TITLE
Задание 1

### ISSUE THREAD

**Issue by readysloth** [DizelforClaSS/-#2]
Ребята! Вы сделали не ассемблерную функцию, а ассемблерную вставку в сишную функцию...
![image](https://user-images.githubusercontent.com/28711485/97781237-fb4d6900-1b9a-11eb-8422-6601bde15d5d.png)

Переписывать не надо, только расскажите тогда про сегменты исполняемого файла.
И как можно оптимизировать ваше решение по скорости (с помощью битовых сдвигов).

**Comment by DizelforClaSS** [comment]
Чтобы оптимизировать работу, в переменной X можно сделать побитовый сдвиг влево на 2 (Х<<2). Все потому, что побитовый сдвиг работает быстрее умножения.

**Comment by DizelforClaSS** [comment]
Если я правильно понял, исполняемый файл делиться на три сегмента. Сегмент данных, стек, и сегмент кода.
Сегмент данных в свою очередь разделяется еще на три части: Data сегмент, куча, bss-сегмент.
Data сегмент: содержит в себе все явно инициализированные переменные. Он делиться на 2 части. RO- то есть переменные только для чтения туда обычно записываются константные значения. RW- часть, сюда записываются все переменные, которые могут измениться во время работы программы.
Bss-сегмент содержит неинициализированные глобальные переменные, а еще статические переменные, которые объявлены без явной инициализации.
Куча- Участок используемый для выделения памяти например malloc и она же очищается с помощью таких команд как free. Растет вниз.

Стек вызовов. Растет вверх, то есть навстречу куче. В стек кладется некоторый набор значений одной функции. Обычно этот набор значений называют фреймом. Так вот, как только вызывается функция в стеке выделяется память под фрейм, как только выходим из функции, стек очищается, вместе с локальными переменными, которые к слову уже размещаются в стеке. Фрейм всегда содержит одно значение-адрес возврата.

Сегмент кода- это текстовая часть, содержащая все исполняемые команды,
обычно используется только для чтения. Также он фиксированного размера.

В той последовательности, в которой я описал сегменты исполняемого файла, располагаются в памяти компьютера.
