### ISSUE TITLE
Вопросы к лабе

### ISSUE THREAD

**Issue by readysloth** [DizelforClaSS/-#3]
# [C (gcc)]

```C
    #include <stdio.h>
    
    int f2(){
      int a=1, b=2, c=3;
    }
    int f1(){
      int a, b, c;
      printf("%i %i %i", a, b, c);
    }
    int main()
    {
        f2();
        f1();
    }
```
[Try it online!][TIO-kgxrmyh2]

Код выше выводит `1 2 3` . Как думаете, почему?

[C (gcc)]: https://gcc.gnu.org/
[TIO-kgxrmyh2]: https://tio.run/##S9ZNT07@/185My85pzQlVcGmuCQlM18vw46LKzOvRCHNSEOzmktBAcROtDXUUUiyNdJRSLY1tuaqhSgwRFIAlAZKWgO5BUVAgTQNJdVMBTBS0oHJasJ05iZm5mlocoE0K4DtsYawDEGs2v//AQ "C (gcc) – Try It Online"

**Comment by DizelforClaSS** [comment]
f2():
push rbp
mov rbp, rsp
mov DWORD PTR [rbp-4], 1
mov DWORD PTR [rbp-8], 2
mov DWORD PTR [rbp-12], 3
nop
pop rbp
ret
.LC0:
.string "%i %i %i"
f1():
push rbp
mov rbp, rsp
sub rsp, 16
mov ecx, DWORD PTR [rbp-12]
mov edx, DWORD PTR [rbp-8]
mov eax, DWORD PTR [rbp-4]
mov esi, eax
mov edi, OFFSET FLAT:.LC0
mov eax, 0
call printf
nop
leave
ret
main:
push rbp
mov rbp, rsp
call f2()
call f1()
mov eax, 0
pop rbp
ret
Если взглянуть на ассемблерный код, то можно заметить, что компилятором gcc  в f2() все переменные заносятся в регистры, а в f1() из этих же регистров, считываются ранее объявленные данные.
